# Generated by Django 5.2 on 2025-05-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_studygroup_user_studygroup_admin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watering',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='plant',
            new_name='study_group',
        ),
    ]
