# Generated by Django 5.2 on 2025-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
