# Generated by Django 5.2 on 2025-05-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='species',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='studygroup',
            old_name='name',
            new_name='title',
        ),
    ]
